[tool.poetry]
name = "kaldi-serve"
version = "0.1.0"
description = "Server component for kaldi based ASRs"
authors = []

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
