# This is a sample model specification file which can be loaded in kaldi-serve
# Here we specify a list of model with extra properties like model name,
# language code etc.

# Compulsory keys are `name', `language' (both used to identify a loaded model)
# and `path'.
[[model]]
name = "general"
language_code = "hi"
path = "./path/to/model/dir"

[[model]]
name = "general"
language_code = "en"
n_decoders = 20  # Defaults to 1 if not specified
path = "./path/to/model/dir"

# A model `path` looks something like the following (for minimal transcription
# only use case):

# ├── conf
# │   ├── ivector_extractor.conf
# │   ├── mfcc.conf
# │   ├── online_cmvn.conf
# │   └── splice.conf
# ├── final.mdl
# ├── HCLG.fst
# ├── ivector_extractor
# │   ├── final.dubm
# │   ├── final.ie
# │   ├── final.mat
# │   └── global_cmvn.stats
# └── words.txt

# The files above have the default kaldi chain model interpretation (with
# ivector also as an input). A few things to notes:
# + `final.mdl` contains the neural net and transition model.
# + `HCLG.fst` is the decoding FST.
# + `words.txt` is a symbol table mapping decoder output ids to words.
# + For feature pipeline, mfcc config is picked from`conf/mfcc.conf`.
# + For ivector, we read the `conf/ivector_extractor.conf` allowing two kinds of
#   paths for params in ivector config.
#   - Absolute like /mnt/model/ivector_extractor/final.mat
#   - Relative to the model-dir, something like ivector_extractor/final.mat