# This is a sample model specification file which can be loaded in kaldi-serve
# Here we specify a list of model with extra properties like model name,
# language code etc.

# At the moment, the model itself is kept as a strict directory tree. This will
# change and finally config parameters will go in this spec file while the main
# model data will be packed in a single archive (pointed to by a path here).

# Compulsory keys are `name', `language' and `path'.
[[model]]
name = "general"
language = "hi"
path = "./path/to/model/dir"

[[model]]
name = "bbq"
language = "en"
n_decoders = 2  # Defaults to 1 if not specified
path = "./path/to/model/dir"